require 'rubygems'
require 'fileutils'

task default: ['install_script']

task :install_script do

  fail "Sty doesnt work on Windows" if Gem.win_platform?

  # Create /usr/local/bin/sty
  src = "#{Dir.pwd}/../../bin/sty"
  dst = '/usr/local/bin/sty'

  #TODO check if /usr/local/bin exists
  begin
    FileUtils.cp(src, dst)
  rescue Errno::EPERM, Errno::EACCES => e
    puts "No permission to create #{dst}, let's try with sudo."
    `sudo cp #{src} #{dst}`
  end

  # Create ~/.sty
  home = File.expand_path('~')
  sty_home = "#{home}/.sty/"
  FileUtils.mkdir_p(sty_home)
  FileUtils.mkdir_p("#{sty_home}/auth-cache")

  # Copy config file examples
  yamls = Dir.glob("#{Dir.pwd}/../../*.yaml")
  dest_yamls = Dir.glob("#{sty_home}/*.yaml").map{|f| File.basename(f)}

  yamls.reject! do |y|
    dest_yamls.include?(File.basename(y))
  end

  FileUtils.cp(yamls, sty_home)

  puts "All done"
end