require 'rubygems'
require 'fileutils'

# Rubygems executable wrapper is not working for sty.
# Thus we install the script using fake extension

task default: ['install_script']

task :install_script do

  fail "Sty doesnt work on Windows" if Gem.win_platform?

  # Create /usr/local/bin/sty
  src = "#{Dir.pwd}/../../bin/sty"
  usr_local_bin = '/usr/local/bin'
  dst = "#{usr_local_bin}/sty"

  #TODO check if /usr/local/bin exists
  puts "There is no #{usr_local_bin}" unless File.exist?(usr_local_bin)

  begin
    FileUtils.cp(src, dst)
  rescue Errno::EPERM, Errno::EACCES => e
    puts "No permission to create #{dst}, let's try with sudo."
    `sudo cp #{src} #{dst}`
  end

  # Create ~/.sty
  home = File.expand_path('~')
  sty_home = "#{home}/.sty/"
  FileUtils.mkdir_p(sty_home)
  FileUtils.mkdir_p("#{sty_home}/auth-cache")

  # Copy config file examples
  yamls = Dir.glob("#{Dir.pwd}/../../*.yaml")
  dest_yamls = Dir.glob("#{sty_home}/*.yaml").map{|f| File.basename(f)}

  yamls.reject! do |y|
    dest_yamls.include?(File.basename(y))
  end

  FileUtils.cp(yamls, sty_home)

  puts "All done"
end